package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// render writes a Markdown feature matrix from ir. The matrix layout:
//
//	| Symbol | Package | Tags | Reason | Source |
//
// Symbol is the fully-qualified name (`Receiver.Method` for methods,
// `Function` for package-level funcs). Tags renders as a sorted,
// space-separated list of bold tokens (` **pro** **mockta** `) so the
// matrix is searchable by tag word. Source is a relative file:line
// reference.
func render(ir *IR) []byte {
	var buf bytes.Buffer

	buf.WriteString("# Feature Matrix\n\n")
	buf.WriteString("Auto-generated by `tools/docgen render`. Do not edit by hand —\n")
	buf.WriteString("rerun `make docs-matrix` after changing source markers.\n\n")
	buf.WriteString("Every row corresponds to a `// libtftest:requires <tag>[,<tag>...] <reason>`\n")
	buf.WriteString("marker found in the repository. The marker grammar and its rationale\n")
	buf.WriteString("are documented in\n")
	buf.WriteString("[INV-0004](investigation/0004-pro-and-oss-feature-matrix-tooling.md).\n\n")

	if len(ir.Markers) == 0 {
		buf.WriteString("_No markers found._\n")
		return buf.Bytes()
	}

	tagsUsed := collectTags(ir)
	buf.WriteString(renderSummary(ir, tagsUsed))
	buf.WriteString("\n")
	buf.WriteString(renderTable(ir))

	return buf.Bytes()
}

func renderTable(ir *IR) string {
	var buf bytes.Buffer
	buf.WriteString("| Symbol | Package | Tags | Reason | Source |\n")
	buf.WriteString("| --- | --- | --- | --- | --- |\n")

	for _, m := range ir.Markers {
		symbol := m.Function
		if m.Receiver != "" {
			symbol = m.Receiver + "." + m.Function
		}
		fmt.Fprintf(&buf, "| `%s` | `%s` | %s | %s | `%s:%d` |\n",
			symbol, m.Package, formatTags(m.Tags), escapePipes(m.Reason),
			m.File, m.Line)
	}
	return buf.String()
}

// renderSummary emits a count-per-tag header so reviewers see at a
// glance how many functions gate on each tag.
func renderSummary(ir *IR, tagsUsed []string) string {
	counts := make(map[string]int, len(tagsUsed))
	for _, m := range ir.Markers {
		for _, t := range m.Tags {
			counts[t]++
		}
	}

	var buf bytes.Buffer
	buf.WriteString("## Summary\n\n")
	fmt.Fprintf(&buf, "%d marker(s) across %d distinct tag(s):\n\n",
		len(ir.Markers), len(tagsUsed))
	for _, t := range tagsUsed {
		fmt.Fprintf(&buf, "- **%s** — %d marker(s)\n", t, counts[t])
	}
	return buf.String()
}

func collectTags(ir *IR) []string {
	seen := make(map[string]struct{})
	for _, m := range ir.Markers {
		for _, t := range m.Tags {
			seen[t] = struct{}{}
		}
	}
	tags := make([]string, 0, len(seen))
	for t := range seen {
		tags = append(tags, t)
	}
	sort.Strings(tags)
	return tags
}

func formatTags(tags []string) string {
	sorted := append([]string(nil), tags...)
	sort.Strings(sorted)
	parts := make([]string, len(sorted))
	for i, t := range sorted {
		parts[i] = "**" + t + "**"
	}
	return strings.Join(parts, " ")
}

func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}
