---
# $schema=https://www.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: libtftest
  title: libtftest
  description: An idiomatic golang library for Terraform testing
  annotations:
    backstage.io/source-location: url:https://github.com/donaldgifford/libtftest
    backstage.io/techdocs-ref: "dir:."
  tags:
    - homelab
    - go
  namespace: default
spec:
  lifecycle: production
  type: library
  owner: donaldgifford
  system: homelab
